model: gemma-3-27b
custom_tasks_file: data/creak/error_prefill_none_100.json
selectors: ["assistant_all"]
layers_to_extract: [25, 32, 39, 46, 53]
batch_size: 8
save_every: 50
output_dir: activations/gemma-3-27b_it/truth_error_prefill
